### ISSUE TITLE
Optimización de configuración RabbitMQ para mejor rendimiento y estabilidad

### ISSUE THREAD

**Issue by dqmdz** [UM-services/UM.tesoreria.sender-service#34]
# Optimización de configuración RabbitMQ para mejor rendimiento y estabilidad

## Descripción
Se requiere optimizar la configuración de RabbitMQ para mejorar el rendimiento, la estabilidad y el uso de recursos del sistema. Los cambios incluyen ajustes en el manejo de conexiones, prefetch counts y configuración de listeners.

### Configuración de RabbitMQ
1. Ajustes de Listener Container Factory
   - Prefetch count: 5
   - Batch size: 5
   - Concurrent consumers: 1
   - Max concurrent consumers: 2

2. Optimización de Cache
   - Channel cache size: 10
   - Connection mode: channel

3. Configuración de Publisher
   - Publisher connection separada
   - Transacciones habilitadas

### Configuración en bootstrap.yml
```yaml
spring:
rabbitmq:
listener:
simple:
prefetch: 5
concurrency: 1
max-concurrency: 2
batch-size: 5
missing-queues-fatal: false
default-requeue-rejected: false
cache:
channel:
size: 10
connection:
mode: channel
```

## Beneficios esperados
- Mejor manejo de recursos
- Mayor estabilidad en las conexiones
- Procesamiento más eficiente de mensajes
- Reducción de sobrecarga en el sistema
- Mejor control de transacciones

## Tipo de cambio
- [x] Optimización de rendimiento
- [x] Configuración de sistema
- [ ] Nueva funcionalidad
- [ ] Breaking change

## Checklist
- [ ] Pruebas de carga
- [ ] Monitoreo de rendimiento
- [ ] Documentación actualizada
- [ ] Verificación de logs
- [ ] Pruebas en ambiente de desarrollo

## Métricas a monitorear
- Uso de memoria
- Tiempo de procesamiento de mensajes
- Tasa de errores
- Uso de conexiones
- Latencia de procesamiento
